image: docker:latest

stages:
  - deploy

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account 1063618009-compute@developer.gserviceaccount.com --key-file=/home/ronaredrum/Downloads/todocase2-e90a2379f181.json
    - gcloud config set project todocase2
    - gcloud builds submit . --config=todocase-depl.yaml
