image: docker:latest

stages:
  - deploy

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo e90a2379f18106e32985b584527aa8a44fa5db38 > todocase2-e90a2379f181.json # Google Cloud service accounts
    - gcloud auth activate-service-account 1063618009-compute@developer.gserviceaccount.com --key-file=todocase2-e90a2379f181.json
    - gcloud config set project todocase2
    - gcloud builds submit . --config=todocase-depl.yaml
