image: docker:latest

stages:
  - deploy

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo $GCP_SERVICE_ACCOUNT > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account 1063618009-compute@developer.gserviceaccount.com --key-file=gcloud-service-key.json
    - gcloud auth configure-docker
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=todocase-depl.yaml
