image: docker:latest

stages:
  - acceptance-tests
  - deploy

include:
  - project: "ronaemre7231/gitlab-ci-files"
    file: "/gauge/acceptance-test.yml" # https://gitlab.com/ronaemre7231/gitlab-ci-files/-/blob/main/gauge/acceptance-test.yml

acceptance-tests:
stage: acceptance-tests
extends: .acceptance-test

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo $GCP_SERVICE_ACCOUNT > todocase2-e90a2379f181.json # Google Cloud service accountss
    - gcloud auth activate-service-account 1063618009-compute@developer.gserviceaccount.com --key-file=todocase2-e90a2379f181.json
    - gcloud auth configure-docker
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME #Run the gcloud build command to build our image
    - gcloud run deploy $SERVICE_NAME --image gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME --region=us-central1 --platform managed --allow-unauthenticated # Run the gcloud run deploy command to deploy our new service

